/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as WalletRouteImport } from "./routes/wallet";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as ReportRouteImport } from "./routes/report";
import { Route as EcosystemRouteImport } from "./routes/ecosystem";
import { Route as CultureRouteImport } from "./routes/culture";
import { Route as IndexRouteImport } from "./routes/index";

const WalletRoute = WalletRouteImport.update({
  id: "/wallet",
  path: "/wallet",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const ReportRoute = ReportRouteImport.update({
  id: "/report",
  path: "/report",
  getParentRoute: () => rootRouteImport,
} as any);
const EcosystemRoute = EcosystemRouteImport.update({
  id: "/ecosystem",
  path: "/ecosystem",
  getParentRoute: () => rootRouteImport,
} as any);
const CultureRoute = CultureRouteImport.update({
  id: "/culture",
  path: "/culture",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/culture": typeof CultureRoute;
  "/ecosystem": typeof EcosystemRoute;
  "/report": typeof ReportRoute;
  "/settings": typeof SettingsRoute;
  "/wallet": typeof WalletRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/culture": typeof CultureRoute;
  "/ecosystem": typeof EcosystemRoute;
  "/report": typeof ReportRoute;
  "/settings": typeof SettingsRoute;
  "/wallet": typeof WalletRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/culture": typeof CultureRoute;
  "/ecosystem": typeof EcosystemRoute;
  "/report": typeof ReportRoute;
  "/settings": typeof SettingsRoute;
  "/wallet": typeof WalletRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/culture" | "/ecosystem" | "/report" | "/settings" | "/wallet";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/culture" | "/ecosystem" | "/report" | "/settings" | "/wallet";
  id: "__root__" | "/" | "/culture" | "/ecosystem" | "/report" | "/settings" | "/wallet";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CultureRoute: typeof CultureRoute;
  EcosystemRoute: typeof EcosystemRoute;
  ReportRoute: typeof ReportRoute;
  SettingsRoute: typeof SettingsRoute;
  WalletRoute: typeof WalletRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/wallet": {
      id: "/wallet";
      path: "/wallet";
      fullPath: "/wallet";
      preLoaderRoute: typeof WalletRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/report": {
      id: "/report";
      path: "/report";
      fullPath: "/report";
      preLoaderRoute: typeof ReportRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ecosystem": {
      id: "/ecosystem";
      path: "/ecosystem";
      fullPath: "/ecosystem";
      preLoaderRoute: typeof EcosystemRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/culture": {
      id: "/culture";
      path: "/culture";
      fullPath: "/culture";
      preLoaderRoute: typeof CultureRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CultureRoute: CultureRoute,
  EcosystemRoute: EcosystemRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  WalletRoute: WalletRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
