/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as WorkshopsRouteImport } from "./routes/workshops";
import { Route as WalletRouteImport } from "./routes/wallet";
import { Route as TasksRouteImport } from "./routes/tasks";
import { Route as SignupRouteImport } from "./routes/signup";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as ResetPasswordRouteImport } from "./routes/reset-password";
import { Route as ReportRouteImport } from "./routes/report";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as LeaderboardRouteImport } from "./routes/leaderboard";
import { Route as EvolutionRouteImport } from "./routes/evolution";
import { Route as EcosystemRouteImport } from "./routes/ecosystem";
import { Route as CultureRouteImport } from "./routes/culture";
import { Route as IndexRouteImport } from "./routes/index";

const WorkshopsRoute = WorkshopsRouteImport.update({
  id: "/workshops",
  path: "/workshops",
  getParentRoute: () => rootRouteImport,
} as any);
const WalletRoute = WalletRouteImport.update({
  id: "/wallet",
  path: "/wallet",
  getParentRoute: () => rootRouteImport,
} as any);
const TasksRoute = TasksRouteImport.update({
  id: "/tasks",
  path: "/tasks",
  getParentRoute: () => rootRouteImport,
} as any);
const SignupRoute = SignupRouteImport.update({
  id: "/signup",
  path: "/signup",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => rootRouteImport,
} as any);
const ReportRoute = ReportRouteImport.update({
  id: "/report",
  path: "/report",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: "/leaderboard",
  path: "/leaderboard",
  getParentRoute: () => rootRouteImport,
} as any);
const EvolutionRoute = EvolutionRouteImport.update({
  id: "/evolution",
  path: "/evolution",
  getParentRoute: () => rootRouteImport,
} as any);
const EcosystemRoute = EcosystemRouteImport.update({
  id: "/ecosystem",
  path: "/ecosystem",
  getParentRoute: () => rootRouteImport,
} as any);
const CultureRoute = CultureRouteImport.update({
  id: "/culture",
  path: "/culture",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/culture": typeof CultureRoute;
  "/ecosystem": typeof EcosystemRoute;
  "/evolution": typeof EvolutionRoute;
  "/leaderboard": typeof LeaderboardRoute;
  "/login": typeof LoginRoute;
  "/report": typeof ReportRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/settings": typeof SettingsRoute;
  "/signup": typeof SignupRoute;
  "/tasks": typeof TasksRoute;
  "/wallet": typeof WalletRoute;
  "/workshops": typeof WorkshopsRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/culture": typeof CultureRoute;
  "/ecosystem": typeof EcosystemRoute;
  "/evolution": typeof EvolutionRoute;
  "/leaderboard": typeof LeaderboardRoute;
  "/login": typeof LoginRoute;
  "/report": typeof ReportRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/settings": typeof SettingsRoute;
  "/signup": typeof SignupRoute;
  "/tasks": typeof TasksRoute;
  "/wallet": typeof WalletRoute;
  "/workshops": typeof WorkshopsRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/culture": typeof CultureRoute;
  "/ecosystem": typeof EcosystemRoute;
  "/evolution": typeof EvolutionRoute;
  "/leaderboard": typeof LeaderboardRoute;
  "/login": typeof LoginRoute;
  "/report": typeof ReportRoute;
  "/reset-password": typeof ResetPasswordRoute;
  "/settings": typeof SettingsRoute;
  "/signup": typeof SignupRoute;
  "/tasks": typeof TasksRoute;
  "/wallet": typeof WalletRoute;
  "/workshops": typeof WorkshopsRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/culture"
    | "/ecosystem"
    | "/evolution"
    | "/leaderboard"
    | "/login"
    | "/report"
    | "/reset-password"
    | "/settings"
    | "/signup"
    | "/tasks"
    | "/wallet"
    | "/workshops";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/culture"
    | "/ecosystem"
    | "/evolution"
    | "/leaderboard"
    | "/login"
    | "/report"
    | "/reset-password"
    | "/settings"
    | "/signup"
    | "/tasks"
    | "/wallet"
    | "/workshops";
  id:
    | "__root__"
    | "/"
    | "/culture"
    | "/ecosystem"
    | "/evolution"
    | "/leaderboard"
    | "/login"
    | "/report"
    | "/reset-password"
    | "/settings"
    | "/signup"
    | "/tasks"
    | "/wallet"
    | "/workshops";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  CultureRoute: typeof CultureRoute;
  EcosystemRoute: typeof EcosystemRoute;
  EvolutionRoute: typeof EvolutionRoute;
  LeaderboardRoute: typeof LeaderboardRoute;
  LoginRoute: typeof LoginRoute;
  ReportRoute: typeof ReportRoute;
  ResetPasswordRoute: typeof ResetPasswordRoute;
  SettingsRoute: typeof SettingsRoute;
  SignupRoute: typeof SignupRoute;
  TasksRoute: typeof TasksRoute;
  WalletRoute: typeof WalletRoute;
  WorkshopsRoute: typeof WorkshopsRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workshops": {
      id: "/workshops";
      path: "/workshops";
      fullPath: "/workshops";
      preLoaderRoute: typeof WorkshopsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/wallet": {
      id: "/wallet";
      path: "/wallet";
      fullPath: "/wallet";
      preLoaderRoute: typeof WalletRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/tasks": {
      id: "/tasks";
      path: "/tasks";
      fullPath: "/tasks";
      preLoaderRoute: typeof TasksRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signup": {
      id: "/signup";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reset-password": {
      id: "/reset-password";
      path: "/reset-password";
      fullPath: "/reset-password";
      preLoaderRoute: typeof ResetPasswordRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/report": {
      id: "/report";
      path: "/report";
      fullPath: "/report";
      preLoaderRoute: typeof ReportRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/leaderboard": {
      id: "/leaderboard";
      path: "/leaderboard";
      fullPath: "/leaderboard";
      preLoaderRoute: typeof LeaderboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/evolution": {
      id: "/evolution";
      path: "/evolution";
      fullPath: "/evolution";
      preLoaderRoute: typeof EvolutionRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/ecosystem": {
      id: "/ecosystem";
      path: "/ecosystem";
      fullPath: "/ecosystem";
      preLoaderRoute: typeof EcosystemRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/culture": {
      id: "/culture";
      path: "/culture";
      fullPath: "/culture";
      preLoaderRoute: typeof CultureRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CultureRoute: CultureRoute,
  EcosystemRoute: EcosystemRoute,
  EvolutionRoute: EvolutionRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  ReportRoute: ReportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TasksRoute: TasksRoute,
  WalletRoute: WalletRoute,
  WorkshopsRoute: WorkshopsRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

import type { getRouter } from "./router.tsx";
import type { startInstance } from "./start.ts";
declare module "@tanstack/react-start" {
  interface Register {
    ssr: true;
    router: Awaited<ReturnType<typeof getRouter>>;
    config: Awaited<ReturnType<typeof startInstance.getOptions>>;
  }
}
